import re
from typing import List

def names_match(name1: str, name2: str) -> bool:
    """Check if two player names match with fuzzy matching"""
    name1_clean = re.sub(r'[^\w\s]', '', name1.lower()).strip()
    name2_clean = re.sub(r'[^\w\s]', '', name2.lower()).strip()
    
    if name1_clean == name2_clean:
        return True
    
    words1 = set(name1_clean.split())
    words2 = set(name2_clean.split())
    
    # Match if at least 2 words in common or if one is a subset of the other
    return len(words1.intersection(words2)) >= 2 or words1.issubset(words2) or words2.issubset(words1)

def find_player_projection(player_name: str, projections: dict[str, float]) -> float:
    """Find player projection with fuzzy name matching"""
    # Direct match first
    if player_name in projections:
        return projections[player_name]
    
    # Fuzzy match
    for proj_name, points in projections.items():
        if names_match(player_name, proj_name):
            return points
    
    return 0.0

def get_bye_weeks() -> dict[int, List[str]]:
    """Get 2025 NFL bye week schedule"""
    return {
        5: ['PIT', 'CHI', 'GB', 'ATL'],
        6: ['HOU', 'MIN'],
        7: ['BAL', 'BUF'],
        8: ['JAX', 'LV', 'DET', 'ARI', 'SEA', 'LAR'],
        9: ['PHI', 'CLE', 'NYJ', 'TB'],
        10: ['KC', 'CIN', 'TEN', 'DAL'],
        11: ['IND', 'NO'],
        12: ['MIA', 'DEN', 'LAC', 'WAS'],
        13: [],  # No bye weeks in Week 13
        14: ['NYG', 'NE', 'CAR', 'SF']
    }

def calculate_combined_player_score(player, weight_projection: float = 0.6, weight_historical: float = 0.4) -> float:
    """
    Calculate a combined score for a player using both projections and historical data.
    
    Args:
        player: Player object with projection and historical data
        weight_projection: Weight given to current projections (0.0-1.0)
        weight_historical: Weight given to historical performance (0.0-1.0)
    
    Returns:
        Combined score for player ranking
    """
    base_score = player.projected_points * weight_projection
    
    if player.season_average > 0:
        historical_score = player.season_average * weight_historical
        
        # Boost for hot recent form
        if player.last_3_weeks_avg > player.season_average * 1.2:
            historical_score *= 1.15
        
        # Boost/penalty for trend
        if player.trend == 'Trending up':
            historical_score *= 1.1
        elif player.trend == 'Trending down':
            historical_score *= 0.9
        
        # Boost for good opponent matchup history
        if player.vs_opponent_games > 0 and player.vs_opponent_avg > player.season_average:
            historical_score *= 1.1
        
        # Slight boost for consistency (especially important for QB/TE)
        if player.consistency_score > 70:
            historical_score *= 1.05
        
        base_score += historical_score
    
    return base_score
def validate_lineup_requirements(available_players: List) -> tuple[bool, str]:
    """
    Validate that we have enough players for a complete lineup.
    
    Returns:
        Tuple of (is_valid, error_message)
    """
    position_counts = {}
    for player in available_players:
        if player.is_playing:
            position_counts[player.position] = position_counts.get(player.position, 0) + 1
    
    # Minimum requirements for a valid lineup
    requirements = {
        'QB': 1,  # Need at least 1 QB
        'RB': 2,  # Need at least 2 RB
        'WR': 2,  # Need at least 2 WR  
        'TE': 1,  # Need at least 1 TE
        'DST': 1,
        'K': 1
    }
    
    missing = []
    for pos, min_needed in requirements.items():
        available = position_counts.get(pos, 0)
        if available < min_needed:
            missing.append(f"{pos}: need {min_needed}, have {available}")
    
    if missing:
        return False, f"Insufficient players: {', '.join(missing)}"
    
    # Check total players (need at least 9 for QB, RB1, RB2, WR1, WR2, TE, FLEX, OP, plus D/ST)
    total_offensive = sum(position_counts.get(pos, 0) for pos in ['QB', 'RB', 'WR', 'TE'])
    if total_offensive < 8:  # 8 offensive players minimum for full lineup
        return False, f"Need at least 8 total offensive players, have {total_offensive}"
    
    return True, "Lineup requirements satisfied"

def _get_current_week_matchups(week: int) -> dict:
    """Get current week team matchups based on complete 2025 NFL schedule."""
    
    matchups_by_week = {1: {'ARI': 'NO',
     'ATL': 'TB',
     'BAL': 'BUF',
     'BUF': 'BAL',
     'CAR': 'JAX',
     'CHI': 'MIN',
     'CIN': 'CLE',
     'CLE': 'CIN',
     'DAL': 'PHI',
     'DEN': 'TEN',
     'DET': 'GB',
     'GB': 'DET',
     'HOU': 'LAR',
     'IND': 'MIA',
     'JAX': 'CAR',
     'KC': 'LAC',
     'LAC': 'KC',
     'LAR': 'HOU',
     'LV': 'NE',
     'MIA': 'IND',
     'MIN': 'CHI',
     'NE': 'LV',
     'NO': 'ARI',
     'NYG': 'WSH',
     'NYJ': 'PIT',
     'PHI': 'DAL',
     'PIT': 'NYJ',
     'SEA': 'SF',
     'SF': 'SEA',
     'TB': 'ATL',
     'TEN': 'DEN',
     'WSH': 'NYG'},
 2: {'ARI': 'CAR',
     'ATL': 'MIN',
     'BAL': 'CLE',
     'BUF': 'NYJ',
     'CAR': 'ARI',
     'CHI': 'DET',
     'CIN': 'JAX',
     'CLE': 'BAL',
     'DAL': 'NYG',
     'DEN': 'IND',
     'DET': 'CHI',
     'GB': 'WSH',
     'HOU': 'TB',
     'IND': 'DEN',
     'JAX': 'CIN',
     'KC': 'PHI',
     'LAC': 'LV',
     'LAR': 'TEN',
     'LV': 'LAC',
     'MIA': 'NE',
     'MIN': 'ATL',
     'NE': 'MIA',
     'NO': 'SF',
     'NYG': 'DAL',
     'NYJ': 'BUF',
     'PHI': 'KC',
     'PIT': 'SEA',
     'SEA': 'PIT',
     'SF': 'NO',
     'TB': 'HOU',
     'TEN': 'LAR',
     'WSH': 'GB'},
 3: {'ARI': 'SF',
     'ATL': 'CAR',
     'BAL': 'DET',
     'BUF': 'MIA',
     'CAR': 'ATL',
     'CHI': 'DAL',
     'CIN': 'MIN',
     'CLE': 'GB',
     'DAL': 'CHI',
     'DEN': 'LAC',
     'DET': 'BAL',
     'GB': 'CLE',
     'HOU': 'JAX',
     'IND': 'TEN',
     'JAX': 'HOU',
     'KC': 'NYG',
     'LAC': 'DEN',
     'LAR': 'PHI',
     'LV': 'WSH',
     'MIA': 'BUF',
     'MIN': 'CIN',
     'NE': 'PIT',
     'NO': 'SEA',
     'NYG': 'KC',
     'NYJ': 'TB',
     'PHI': 'LAR',
     'PIT': 'NE',
     'SEA': 'NO',
     'SF': 'ARI',
     'TB': 'NYJ',
     'TEN': 'IND',
     'WSH': 'LV'},
 4: {'ARI': 'SEA',
     'ATL': 'WSH',
     'BAL': 'KC',
     'BUF': 'NO',
     'CAR': 'NE',
     'CHI': 'LV',
     'CIN': 'DEN',
     'CLE': 'DET',
     'DAL': 'GB',
     'DEN': 'CIN',
     'DET': 'CLE',
     'GB': 'DAL',
     'HOU': 'TEN',
     'IND': 'LAR',
     'JAX': 'SF',
     'KC': 'BAL',
     'LAC': 'NYG',
     'LAR': 'IND',
     'LV': 'CHI',
     'MIA': 'NYJ',
     'MIN': 'PIT',
     'NE': 'CAR',
     'NO': 'BUF',
     'NYG': 'LAC',
     'NYJ': 'MIA',
     'PHI': 'TB',
     'PIT': 'MIN',
     'SEA': 'ARI',
     'SF': 'JAX',
     'TB': 'PHI',
     'TEN': 'HOU',
     'WSH': 'ATL'},
 5: {'ARI': 'TEN',
     'BAL': 'HOU',
     'BUF': 'NE',
     'CAR': 'MIA',
     'CIN': 'DET',
     'CLE': 'MIN',
     'DAL': 'NYJ',
     'DEN': 'PHI',
     'DET': 'CIN',
     'HOU': 'BAL',
     'IND': 'LV',
     'JAX': 'KC',
     'KC': 'JAX',
     'LAC': 'WSH',
     'LAR': 'SF',
     'LV': 'IND',
     'MIA': 'CAR',
     'MIN': 'CLE',
     'NE': 'BUF',
     'NO': 'NYG',
     'NYG': 'NO',
     'NYJ': 'DAL',
     'PHI': 'DEN',
     'SEA': 'TB',
     'SF': 'LAR',
     'TB': 'SEA',
     'TEN': 'ARI',
     'WSH': 'LAC'},
 6: {'ARI': 'IND',
     'ATL': 'BUF',
     'BAL': 'LAR',
     'BUF': 'ATL',
     'CAR': 'DAL',
     'CHI': 'WSH',
     'CIN': 'GB',
     'CLE': 'PIT',
     'DAL': 'CAR',
     'DEN': 'NYJ',
     'DET': 'KC',
     'GB': 'CIN',
     'IND': 'ARI',
     'JAX': 'SEA',
     'KC': 'DET',
     'LAC': 'MIA',
     'LAR': 'BAL',
     'LV': 'TEN',
     'MIA': 'LAC',
     'NE': 'NO',
     'NO': 'NE',
     'NYG': 'PHI',
     'NYJ': 'DEN',
     'PHI': 'NYG',
     'PIT': 'CLE',
     'SEA': 'JAX',
     'SF': 'TB',
     'TB': 'SF',
     'TEN': 'LV',
     'WSH': 'CHI'},
 7: {'ARI': 'GB',
     'ATL': 'SF',
     'CAR': 'NYJ',
     'CHI': 'NO',
     'CIN': 'PIT',
     'CLE': 'MIA',
     'DAL': 'WSH',
     'DEN': 'NYG',
     'DET': 'TB',
     'GB': 'ARI',
     'HOU': 'SEA',
     'IND': 'LAC',
     'JAX': 'LAR',
     'KC': 'LV',
     'LAC': 'IND',
     'LAR': 'JAX',
     'LV': 'KC',
     'MIA': 'CLE',
     'MIN': 'PHI',
     'NE': 'TEN',
     'NO': 'CHI',
     'NYG': 'DEN',
     'NYJ': 'CAR',
     'PHI': 'MIN',
     'PIT': 'CIN',
     'SEA': 'HOU',
     'SF': 'ATL',
     'TB': 'DET',
     'TEN': 'NE',
     'WSH': 'DAL'},
 8: {'ATL': 'MIA',
     'BAL': 'CHI',
     'BUF': 'CAR',
     'CAR': 'BUF',
     'CHI': 'BAL',
     'CIN': 'NYJ',
     'CLE': 'NE',
     'DAL': 'DEN',
     'DEN': 'DAL',
     'GB': 'PIT',
     'HOU': 'SF',
     'IND': 'TEN',
     'KC': 'WSH',
     'LAC': 'MIN',
     'MIA': 'ATL',
     'MIN': 'LAC',
     'NE': 'CLE',
     'NO': 'TB',
     'NYG': 'PHI',
     'NYJ': 'CIN',
     'PHI': 'NYG',
     'PIT': 'GB',
     'SF': 'HOU',
     'TB': 'NO',
     'TEN': 'IND',
     'WSH': 'KC'},
 9: {'ARI': 'DAL',
     'ATL': 'NE',
     'BAL': 'MIA',
     'BUF': 'KC',
     'CAR': 'GB',
     'CHI': 'CIN',
     'CIN': 'CHI',
     'DAL': 'ARI',
     'DEN': 'HOU',
     'DET': 'MIN',
     'GB': 'CAR',
     'HOU': 'DEN',
     'IND': 'PIT',
     'JAX': 'LV',
     'KC': 'BUF',
     'LAC': 'TEN',
     'LAR': 'NO',
     'LV': 'JAX',
     'MIA': 'BAL',
     'MIN': 'DET',
     'NE': 'ATL',
     'NO': 'LAR',
     'NYG': 'SF',
     'PIT': 'IND',
     'SEA': 'WSH',
     'SF': 'NYG',
     'TEN': 'LAC',
     'WSH': 'SEA'},
 10: {'ARI': 'SEA',
      'ATL': 'IND',
      'BAL': 'MIN',
      'BUF': 'MIA',
      'CAR': 'NO',
      'CHI': 'NYG',
      'CLE': 'NYJ',
      'DEN': 'LV',
      'DET': 'WSH',
      'GB': 'PHI',
      'HOU': 'JAX',
      'IND': 'ATL',
      'JAX': 'HOU',
      'LAC': 'PIT',
      'LAR': 'SF',
      'LV': 'DEN',
      'MIA': 'BUF',
      'MIN': 'BAL',
      'NE': 'TB',
      'NO': 'CAR',
      'NYG': 'CHI',
      'NYJ': 'CLE',
      'PHI': 'GB',
      'PIT': 'LAC',
      'SEA': 'ARI',
      'SF': 'LAR',
      'TB': 'NE',
      'WSH': 'DET'},
 11: {'ARI': 'SF',
      'ATL': 'CAR',
      'BAL': 'CLE',
      'BUF': 'TB',
      'CAR': 'ATL',
      'CHI': 'MIN',
      'CIN': 'PIT',
      'CLE': 'BAL',
      'DAL': 'LV',
      'DEN': 'KC',
      'DET': 'PHI',
      'GB': 'NYG',
      'HOU': 'TEN',
      'JAX': 'LAC',
      'KC': 'DEN',
      'LAC': 'JAX',
      'LAR': 'SEA',
      'LV': 'DAL',
      'MIA': 'WSH',
      'MIN': 'CHI',
      'NE': 'NYJ',
      'NYG': 'GB',
      'NYJ': 'NE',
      'PHI': 'DET',
      'PIT': 'CIN',
      'SEA': 'LAR',
      'SF': 'ARI',
      'TB': 'BUF',
      'TEN': 'HOU',
      'WSH': 'MIA'},
 12: {'ARI': 'JAX',
      'ATL': 'NO',
      'BAL': 'NYJ',
      'BUF': 'HOU',
      'CAR': 'SF',
      'CHI': 'PIT',
      'CIN': 'NE',
      'CLE': 'LV',
      'DAL': 'PHI',
      'DET': 'NYG',
      'GB': 'MIN',
      'HOU': 'BUF',
      'IND': 'KC',
      'JAX': 'ARI',
      'KC': 'IND',
      'LAR': 'TB',
      'LV': 'CLE',
      'MIN': 'GB',
      'NE': 'CIN',
      'NO': 'ATL',
      'NYG': 'DET',
      'NYJ': 'BAL',
      'PHI': 'DAL',
      'PIT': 'CHI',
      'SEA': 'TEN',
      'SF': 'CAR',
      'TB': 'LAR',
      'TEN': 'SEA'},
 13: {'ARI': 'TB',
      'ATL': 'NYJ',
      'BAL': 'CIN',
      'BUF': 'PIT',
      'CAR': 'LAR',
      'CHI': 'PHI',
      'CIN': 'BAL',
      'CLE': 'SF',
      'DAL': 'KC',
      'DEN': 'WSH',
      'DET': 'GB',
      'GB': 'DET',
      'HOU': 'IND',
      'IND': 'HOU',
      'JAX': 'TEN',
      'KC': 'DAL',
      'LAC': 'LV',
      'LAR': 'CAR',
      'LV': 'LAC',
      'MIA': 'NO',
      'MIN': 'SEA',
      'NE': 'NYG',
      'NO': 'MIA',
      'NYG': 'NE',
      'NYJ': 'ATL',
      'PHI': 'CHI',
      'PIT': 'BUF',
      'SEA': 'MIN',
      'SF': 'CLE',
      'TB': 'ARI',
      'TEN': 'JAX',
      'WSH': 'DEN'},
 14: {'ARI': 'LAR',
      'ATL': 'SEA',
      'BAL': 'PIT',
      'BUF': 'CIN',
      'CHI': 'GB',
      'CIN': 'BUF',
      'CLE': 'TEN',
      'DAL': 'DET',
      'DEN': 'LV',
      'DET': 'DAL',
      'GB': 'CHI',
      'HOU': 'KC',
      'IND': 'JAX',
      'JAX': 'IND',
      'KC': 'HOU',
      'LAC': 'PHI',
      'LAR': 'ARI',
      'LV': 'DEN',
      'MIA': 'NYJ',
      'MIN': 'WSH',
      'NO': 'TB',
      'NYJ': 'MIA',
      'PHI': 'LAC',
      'PIT': 'BAL',
      'SEA': 'ATL',
      'TB': 'NO',
      'TEN': 'CLE',
      'WSH': 'MIN'},
 15: {'ARI': 'HOU',
      'ATL': 'TB',
      'BAL': 'CIN',
      'BUF': 'NE',
      'CAR': 'NO',
      'CHI': 'CLE',
      'CIN': 'BAL',
      'CLE': 'CHI',
      'DAL': 'MIN',
      'DEN': 'GB',
      'DET': 'LAR',
      'GB': 'DEN',
      'HOU': 'ARI',
      'IND': 'SEA',
      'JAX': 'NYJ',
      'KC': 'LAC',
      'LAC': 'KC',
      'LAR': 'DET',
      'LV': 'PHI',
      'MIA': 'PIT',
      'MIN': 'DAL',
      'NE': 'BUF',
      'NO': 'CAR',
      'NYG': 'WSH',
      'NYJ': 'JAX',
      'PHI': 'LV',
      'PIT': 'MIA',
      'SEA': 'IND',
      'SF': 'TEN',
      'TB': 'ATL',
      'TEN': 'SF',
      'WSH': 'NYG'},
 16: {'ARI': 'ATL',
      'ATL': 'ARI',
      'BAL': 'NE',
      'BUF': 'CLE',
      'CAR': 'TB',
      'CHI': 'GB',
      'CIN': 'MIA',
      'CLE': 'BUF',
      'DAL': 'LAC',
      'DEN': 'JAX',
      'DET': 'PIT',
      'GB': 'CHI',
      'HOU': 'LV',
      'IND': 'SF',
      'JAX': 'DEN',
      'KC': 'TEN',
      'LAC': 'DAL',
      'LAR': 'SEA',
      'LV': 'HOU',
      'MIA': 'CIN',
      'MIN': 'NYG',
      'NE': 'BAL',
      'NO': 'NYJ',
      'NYG': 'MIN',
      'NYJ': 'NO',
      'PHI': 'WSH',
      'PIT': 'DET',
      'SEA': 'LAR',
      'SF': 'IND',
      'TB': 'CAR',
      'TEN': 'KC',
      'WSH': 'PHI'},
 17: {'ARI': 'CIN',
      'ATL': 'LAR',
      'BAL': 'GB',
      'BUF': 'PHI',
      'CAR': 'SEA',
      'CHI': 'SF',
      'CIN': 'ARI',
      'CLE': 'PIT',
      'DAL': 'WSH',
      'DEN': 'KC',
      'DET': 'MIN',
      'GB': 'BAL',
      'HOU': 'LAC',
      'IND': 'JAX',
      'JAX': 'IND',
      'KC': 'DEN',
      'LAC': 'HOU',
      'LAR': 'ATL',
      'LV': 'NYG',
      'MIA': 'TB',
      'MIN': 'DET',
      'NE': 'NYJ',
      'NO': 'TEN',
      'NYG': 'LV',
      'NYJ': 'NE',
      'PHI': 'BUF',
      'PIT': 'CLE',
      'SEA': 'CAR',
      'SF': 'CHI',
      'TB': 'MIA',
      'TEN': 'NO',
      'WSH': 'DAL'},
 18: {'ARI': 'LAR',
      'ATL': 'NO',
      'BAL': 'PIT',
      'BUF': 'NYJ',
      'CAR': 'TB',
      'CHI': 'DET',
      'CIN': 'CLE',
      'CLE': 'CIN',
      'DAL': 'NYG',
      'DEN': 'LAC',
      'DET': 'CHI',
      'GB': 'MIN',
      'HOU': 'IND',
      'IND': 'HOU',
      'JAX': 'TEN',
      'KC': 'LV',
      'LAC': 'DEN',
      'LAR': 'ARI',
      'LV': 'KC',
      'MIA': 'NE',
      'MIN': 'GB',
      'NE': 'MIA',
      'NO': 'ATL',
      'NYG': 'DAL',
      'NYJ': 'BUF',
      'PHI': 'WSH',
      'PIT': 'BAL',
      'SEA': 'SF',
      'SF': 'SEA',
      'TB': 'CAR',
      'TEN': 'JAX',
      'WSH': 'PHI'}}
    
    return matchups_by_week.get(week, {})